title:        "Ky4eryavii_Pon4o GitHub"
description:  "ðŸ‘¾/ðŸ™ƒ/ðŸŽ®"
remote_theme: "dracula/gh-pages"
show_header: false


socials:
  facebook: "Ky4eryavii.Pon4o" # string, example: Ky4eryavii.Pon4o
  twitter: "" # string, example: somiibo
  youtube: "" # string, example: somiibo
  tumblr: "patap" # string, example: somiibo
